milk1:
  model: milk
  model_type: urdf
  position: [-1.5, -0.5, 1.02]
  orientation: [0, 0, 0]

milk2:
  model: milk
  model_type: urdf
  position: [-1.5, -1.8, 1.5 ]
  orientation: [0, 0, 1.570796]

milk3:
  model: milk
  model_type: urdf
  position: [3.9, -1.8, 1.5 ]
  orientation: [0, 0, 1.570796]

salt:
  model: salt
  model_type: urdf
  position: [ -1.5, -1.0, 1.02 ]
  orientation: [0, 0, 1.570796]

tomato_soup:
  model: tomato_soup
  model_type: urdf
  position: [-1.5, -0.2, 1]
  orientation: [0, 0, 1.570796]

zwieback:
  model: zwieback
  model_type: urdf
  position: [-1.5, 0.25, 1]
  orientation: [0, 0, 1.570796]

tomato_sauce:
  model: tomato_sauce
  model_type: urdf
  position: [-1.7, -0.1, 1]
  orientation: [0, 0, 1.570796]

#cb_4x3:
#  model: cb_4x3
#  model_type: model
#  position: [-0.7, -0.1, 1]
#  orientation: [1.56, 0, 1.56]

#cb_9x6:
#  model: cb_9x6
#  model_type: model
#  position: [-0.7, -0.1, 1]
#  orientation: [1.56, 0, 1.56]

table_ikea:
  model: table_ikea
  model_type: urdf.xacro
  position: [1.5,-1.5, 0]
  orientation: [0, 0, 0]

bookcase:
  model: bookcase
  model_type: urdf.xacro
  position: [3.95, -1.8, 0]
  orientation: [0, 0, 0]

chair:
  model: chair
  model_type: urdf.xacro
  position: [0.7, 1.2, 0.1]
  orientation: [0, 0, 1.5708]

cabinet:
  model: cabinet
  model_type: urdf.xacro
  position: [0,1.35,0]
  orientation: [0, 0, 0]

cabinet_with_door:
  model: cabinet_with_door
  model_type: urdf.xacro
  position: [4.05, -2.8, 0]
  orientation: [0, 0, 0]

couch:
  model: couch
  model_type: urdf.xacro
  position: [3.6,0.6,0]
  orientation: [0, 0,-1.57079]

#QRCode:
#  model: QRCode
#  model_type: urdf.xacro
#  position: [-1.34,-1.7,2]
#  orientation: [0,0,0]

